# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: 🔄 Update Visitor Counter

on:
  # Trigger manually
  workflow_dispatch:
  # Run every hour (adjust as needed)
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write   # allow committing back to repo

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"

      # 3. Install dependencies if requirements.txt exists
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # 4. Run visitor counter script
      - name: Run counter.py
        run: python counter.py

      # 5. Check if counter.json or counter.svg changed
      - name: Check for changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add counter.json counter.svg || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

      # 6. Commit & push changes
      - name: Commit and push
        run: |
          git commit -m "🔄 Update visitor counter [skip ci]"
          git push
