name: Update Visitor Counter

on:
  workflow_dispatch:   # allows manual trigger
  schedule:            # run every 30 minutes
    - cron: "*/30 * * * *"

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      # 3. Install dependencies (if any)
      - name: Install dependencies
        run: pip install -r requirements.txt || true

      # 4. Run counter script
      - name: Run visitor counter
        run: python counter.py

      # 5. Commit & push changes
      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add counter.json counter.svg
          git commit -m "🔄 Update visitor counter"
          git push
